db:
  name: oa_data
  addr: 49.235.180.218
  username: root
  password: 123456

redis:
  Host: 49.235.180.218:6379
  Password: guyu1998
  MaxIdle: 30
  MaxActive: 30
  IdleTimeout: 200

server:
  Port: :19999
  BufSize: 109600

FileServer:
  Addr: 49.235.180.218:50001

kafka:
  ConsumerAddr: 49.235.180.218:9092
  ProductAddr: 49.235.180.218:9092
  TriggerTopic: trigger_message
  ActionTpoic: action_message
